GET http://localhost:4321/authors?page=1&size=5

### Recuperar una author por id
GET http://localhost:4321/authors/2

###
POST http://localhost:4321/authors
Content-Type: application/json

{
  "name": "Isabel",
  "nationality": "mexicana",
  "birthDay": "1942-08-02"
}

###
DELETE http://localhost:4321/authors/4

### Actualizar un author
PATCH http://localhost:4321/authors/1
Content-Type: application/json

{
  "name":"Hola"
}

### Traerme todos los libros
GET http://localhost:4321/books?page=2&size=5

### Recuperar un libro por id
GET http://localhost:4321/books?year=1987

###
POST http://localhost:4321/books
Content-Type: application/json

{

  "title": "Isabel Allende",
  "description": "Chilena",
  "publishedYear": 2020,
  "authorId": 1
}

###
DELETE http://localhost:4321/books/105

### Actualizar una libro
PATCH http://localhost:4321/books/101
Content-Type: application/json

{
  "title":"Hola"
}